# Generated by Django 3.0.2 on 2020-03-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.IntegerField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('emergency_contact1', models.IntegerField(max_length=12)),
                ('emergency_contact2', models.IntegerField(max_length=12)),
                ('emergency_contact3', models.IntegerField(max_length=12)),
                ('emergency_contact4', models.IntegerField(max_length=12)),
                ('emergency_contact5', models.IntegerField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
