# Generated by Django 3.0.2 on 2020-03-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200307_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='id',
        ),
        migrations.AlterField(
            model_name='women',
            name='phone_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
