# Generated by Django 3.0.2 on 2020-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='helped',
            field=models.BooleanField(default=False),
        ),
    ]
