# Generated by Django 3.0.2 on 2020-03-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_crime_helped'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.Crime')),
            ],
        ),
    ]
