# Generated by Django 3.0.2 on 2020-03-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0003_crimeimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrimeImages',
        ),
    ]
