# Generated by Django 3.0.4 on 2020-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0005_crimeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='address',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
