# Generated by Django 3.0.4 on 2020-03-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0007_crime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
